version: '3.8'

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql-with-keycloak
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloakuser
      MYSQL_PASSWORD: keycloakpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - keycloak_network
    ports:
      - "3039:3306"  # Maps host port 3039 to container port 3306 (MySQL default)

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: keycloak
    environment:
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloakuser
      DB_PASSWORD: keycloakpassword
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpassword
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloakuser
      KC_DB_PASSWORD: keycloakpassword
      KEYCLOAK_ADMIN: admin26
      KEYCLOAK_ADMIN_PASSWORD: admin26
    ports:
      - 8084:8080
    depends_on:
      - mysql
    networks:
      - keycloak_network
    command: ["start-dev"]

volumes:
  mysql_data:

networks:
  keycloak_network:

